name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure the run
      run: |
        cp .env.template .env
        cp docker-compose.cli-sw.yml docker-compose.yml
    - name: Build the Docker Salad client
      run: docker build -t enigmampc/salad_client .
    - name: Run tests
      run: |
        NODES=2 SGX_MODE=SW docker-compose -f docker-compose.yml -f docker-compose.salad.yml up --scale core=2 --scale p2p=2 --exit-code-from salad & 
        until docker ps -a | grep salad >/dev/null 2>&1; do sleep 5; done
        sleep 180 && echo "Network ready, starting salad tests"
        docker-compose -f docker-compose.yml -f docker-compose.salad.yml exec -T salad yarn test
